### ISSUE TITLE
FTBFS with unchanged rebuild

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/ubuntu-frame-osk#37]
Attempting a rebuild today (following a "contains outdated Ubuntu packages" notification) gives the following error:

```
Program msgfmt found: NO

../src/data/meson.build:15:5: ERROR: Program 'msgfmt' not found or not executable
```

As well as the immediate problem, this means that we cannot reliably control the build content.

**Comment by wmww** [comment]
It seems old version of the `fragile` crate [have been yanked](https://crates.io/crates/fragile/0.3.0), which `gio` depends on. You should still be able to download them, however. Investigating why this is causing a problem.

**Comment by wmww** [comment]
Ah! https://gitlab.gnome.org/World/Phosh/squeekboard/-/commit/d19050e06d2ecc5218e50e9ef3a5279afa0daff8 fixes this. There are merge conflicts, but I should be able to use that as the basis for a patch.

**Comment by wmww** [comment]
There's a new Squeekboard version, v1.17.0. It also fails, but cherry-picking that fix applies without conflicts and we want to bump to it anyway, so using that.

**Comment by AlanGriffiths** [comment]
OK, so this should be transient
