### ISSUE TITLE
Not working with 23.04 apps?

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/ubuntu-frame-osk#50]
I noticed this while testing on 23.04. (The same scenario works on 22.04LTS)

1. Snap install `frame-it`, `ubuntu-frame`, `ubuntu-frame-osk`
2. `snap connect ubuntu-frame-osk:wayland`
3. `snap set frame-it osk=enable`
4. `frame-it gedit`

**Expect:** OSK appears
**Actual:** OSK doesn't appear

Other apps (e.g. kgx also show this behaviour)

**Comment by Saviq** [comment]
Works for me in a live Lunar desktop…

**Comment by AlanGriffiths** [comment]
Ah!

Works if I switch to GNOME desktop, so this is probably a problem with Miriway session

**Comment by wmww** [comment]
Perhaps it's something like `GTK_IM_MODULE`?

`GTK_IM_MODULE=xim gedit` -> doesn't work
`GTK_IM_MODULE=wayland gedit` -> works
